name: Build Dev Image

on: workflow_dispatch
jobs:
  build-only:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Image
        runs: docker build . -t test/test
