name: Docker Image CI

on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - run: ls .
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: package2
        run: docker buildx build --push --cache-from type=registry,ref=harilab/test7 --cache-to type=registry,ref=harilab/test7,mode=max . -t harilab/test7:${{github.run_number}}
      # - name: package
      #   uses: docker/build-push-action@v3
      #   with:
      #     context: .
      #     push: true
      #     tags: ${{github.run_number}}
      #     cache-to: type=registry,ref=harilab/test5,mode=max
      #     cache-from: type=registry,ref=harilab/test5
