name: Docker Image CI

on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - id: cache-docker
        uses: actions/cache@v3
        env:
          CACHE_KEY_PREFIX: ${{ runner.os }}-docker-cache-
          CACHE_KEY: ${{ runner.os }}-docker-cache-${{hashFiles('Dockerfile','package-lock.json')}}
        with:
          path: /tmp/docker-registry
          key: ${{ env.CACHE_KEY }}
          restore-keys: ${{env.CACHE_KEY_PREFIX}}
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: package
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{github.run_number}}
          cache-to: type=registry,ref=harilab/test5,mode=max
          cache-from: type=registry,ref=harilab/test5
